ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

# The urls of the main app.
from landing.views import Custom404

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('landing.urls')),
                  path('order/', include('order.urls')),
                  path('product/', include('product.urls')),
                  path('customer/', include('customer.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = Custom404.as_view()
# Handling 404 error

landing/urls.py
from django.urls import path

from landing.views import IndexView, ContactView

#  The urls of the landing page
app_name = 'landing'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('contact/', ContactView.as_view(), name='contact'),

]

order/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from order.views import AddCard, OrderItemList, DeleteOrderItem, UpdateOrderItem, CouponView, CouponImplantView

router = DefaultRouter()
router.register('orderitem', AddCard)
# urlpatterns = router.urls

# The urls of orders app
urlpatterns = [
    path('', include(router.urls), ),
    path('order/', OrderItemList.as_view(), name='orders_list'),
    path('delete/<int:pk>', DeleteOrderItem.as_view(), name='delete_item'),
    path('update/<int:pk>', UpdateOrderItem.as_view(), name='update_item'),
    path('coupon_get/<int:pk>', CouponView.as_view(), name='coupon_get'),
    path('coupon/<int:pk>', CouponImplantView.as_view(), name='coupon'),

]

templates/base/_base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% include 'base/_cdn.html' %}
    {% block extra %}{% endblock %}
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
{% include 'base/_navbar.html' %}
{% block body %}
{% endblock %}
{#{% include 'base/_footer.html' %}#}
</body>
</html>

templates/base/_cdn.html
{% load static %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
      integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js"
        integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
        crossorigin="anonymous"></script>

<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<link href="{% static 'gorbeh/css/gorbeh-icons.min.css' %}" rel="stylesheet">
<link rel="icon" type="image/x-icon" href="{% static 'logo.png' %}">

templates/base/_footer.html
{% load static %}
<link rel="stylesheet" href="{% static 'CSS/footer.css' %}">
<footer>
    <div class="footer-content">
        <h3>Foolish Developer</h3>
        <p>Raj Template is a blog website where you will find great tutorials on web design and development. Here each
            tutorial is beautifully described step by step with the required source code.</p>
        <ul class="socials">
            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
            <li><a href="#"><i class="fa fa-youtube"></i></a></li>
            <li><a href="#"><i class="fa fa-linkedin-square"></i></a></li>
        </ul>
    </div>
    <div class="footer-bottom">
        <p>copyright &copy; <a href="#">Foolish Developer</a></p>
        <div class="footer-menu">
            <ul class="f-menu">
                <li><a href="">Home</a></li>
                <li><a href="">About</a></li>
                <li><a href="">Contact</a></li>
                <li><a href="">Blog</a></li>
            </ul>
        </div>
    </div>

</footer>

templates/base/_navbar.html
{% load static %}

{#<link#}
{#        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"#}
{#        rel="stylesheet"#}
{#/>#}
{#<!-- Google Fonts -->#}
{#<link#}
{#        href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"#}
{#        rel="stylesheet"#}
{#/>#}
{#<!-- MDB -->#}
{#<link#}
{#        href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.11.0/mdb.min.css"#}
{#        rel="stylesheet"#}
{#/>#}
{#<header class="header-area">#}
{#    <!-- site-navbar start -->#}
{#    <div class="navbar-area">#}
{#        <div class="container">#}
{#            <nav class="site-navbar">#}
{#                <!-- site logo -->#}
{#                <a href="#home" class="site-logo"><img width="54px" src="{% static 'logo.png' %}" alt=""></a>#}
{##}
{#                <!-- site menu/nav -->#}
{#                <ul>#}
{#                {% if request.user.is_authenticated %}<li><a style="" href="#">Welcome {{ user.username }}</a></li>{% endif %}#}
{#                <li><a style="" href="{% url 'orders_list' %}">Card</a></li>#}
{#                    <li><a style="display:{% if request.user.is_authenticated %}flex{% else %}none{% endif %}"#}
{#                           href="{% url 'customer_logout' %}">Logout</a></li>#}
{#                    <li><a style="display:{% if request.user.is_authenticated %}none{% else %}flex{% endif %}" href="{% url 'customer_login' %}">Login / SignUp</a></li>#}
{#                    <li><a href="{% url 'product_list' %}">Shop</a></li>#}
{#                    <li><a href="#">service</a></li>#}
{#                    <li><a href="{% url 'landing:index' %}">home</a></li>#}
{#                </ul>#}
{##}
{#                <!-- nav-toggler for mobile version only -->#}
{#                <button class="nav-toggler">#}
{#                    <span></span>#}
{#                </button>#}
{#            </nav>#}
{#        </div>#}
{#    </div><!-- navbar-area end -->#}
{##}
{#</header>#}
<style>
    .badge {
        padding-left: 9px;
        padding-right: 9px;
        -webkit-border-radius: 9px;
        -moz-border-radius: 9px;
        border-radius: 9px;
    }

    .label-warning[href],
    .badge-warning[href] {
        background-color: #c67605;
    }

    #lblCartCount {
        font-size: 12px;
        background: rgba(104, 189, 210, 0.71);
        color: #fff;
        padding: 0 5px;
        vertical-align: top;
        margin-left: -5px;
    }
</style>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a href="" class="site-logo"><img width="45px" src="{% static 'logo.png' %}" alt=""></a>

    <div class="d-flex flex-row order-2 order-lg-3">
        <ul class="navbar-nav d-flex flex-row">
            <li class="nav-item">
                <a class="nav-link p-2" href="{% url 'orders_list' %}">
                    <i style="font-size:1.5rem" class="fa fa-shopping-cart" aria-hidden="true"> Cart</i>
                    <span class='badge badge-warning' id='lblCartCount'>{{ number }}</span>

                </a>
            </li>
            <li class="nav-item d-block d-lg-none">
                <a class="nav-link p-2" href="#" data-toggle="collapse" data-target="#nav">
                    <i class="fa fa-bars" aria-hidden="true"></i>
                </a>
            </li>
        </ul>
    </div>

    <div class="collapse navbar-collapse order-3 order-lg-2" id="nav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'landing:index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
                    <li class="nav-item active">
                <a class="nav-link" href="{% url 'landing:contact' %}">ContactUs <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'product_list' %}">Shop</a>
            </li>
            {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
                        Welcome {{ user.username|title }}
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'panel' %}">
                            Go to Panel
                        </a>
                        <a class="dropdown-item" href="{% url 'customer_logout' %}">Logout</a>
                    </div>
                </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" style="display:{% if request.user.is_authenticated %}none{% else %}flex{% endif %}"
                   href="{% url 'customer_login' %}">
                    Login/SignUp
                </a>
            </li>

        </ul>
    </div>


</nav>